version: "3"

services: 
    web:
        build: .
        
        ports: 
            - "3000:5000"

        volumes:
            - .:/code      
        
        environment:
            FLASK_ENV: development